keyword: "MAIN"           
gap_cutoff: 0.25
random_seed: 42
num_seeds: 4
outdir: "/scratch/users/gelnesr/afcluster" # output directory
tmpdir: "/scratch/users/gelnesr/tmp/msas" # temporary directory for msas

cluster_method: "dbscan"

dbscan:
  min_samples: 10
  eps_val: null           
  min_eps: 3
  max_eps: 20.0
  eps_step: 0.5 

afcluster:
  num_seeds: 4
  use_dropout: True
  amber: False
  templates: False
  num_recycle: 3
  num_relax: 0
  
path_vars:
  PATH: "/scratch/users/gelnesr/tools/localcolabfold/colabfold-conda/bin:$PATH" # path to colabfold
  XDG_CACHE_HOME: "/scratch/users/gelnesr/cache" # path to xdg cache  
  MPLCONFIGDIR: "/scratch/users/gelnesr/cache" # path to matplotlib cache
